#!/usr/bin/env bash

input="$1"
genome="$2"
output="$3"
outputbg="${output%%.bw}.bedgraph"

bedtools genomecov -bg -ibam "$input" -g "$genome" > "$outputbg"
bedGraphToBigWig "$outputbg" "$genome" "$output"
