#!/usr/bin/env bash

get_num_threads() {
    < /proc/cpuinfo grep processor | wc -l
}

unpacker() {
    case "$1" in
        *.gz)
            echo 'gzip -dc'
            ;;
        *)
            echo cat
    esac
}

max_alignments=50
num_threads=$(get_num_threads)
mapper=bowtie2

index="$1"
input="$2"
output="$3"

echo >&2 "Input:  $input"
echo >&2 "Output: $output"

mkdir -p "$(dirname "$output")"

$(unpacker "$input") "$input" \
| $mapper \
    -k $max_alignments \
    --threads $num_threads \
    -x "$index" \
    -q \
    -U - \
| samtools view -Sb -F 0x4 - \
| samtools sort - "${output%.bam}"

samtools index "$output"
