#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

get_num_threads() {
    < /proc/cpuinfo grep processor | wc -l
}

max_alignments=50
num_threads=$(get_num_threads)
mapper=bowtie
# Not working on compute nodes at the moment.
#scratch_base='/gpfs/nobackup/marioni/konrad'
scratch_base='./scratch'
scratch_dir="$scratch_base/$(uuidgen)"
mkdir -p "$scratch_dir"

index="$1"
input="$2"
output="$3"
tmp_output="$scratch_dir/$(basename "$output")"
max_mem=$((32 * 1024 * 1024 * 1024))

echo >&2 "Input:  $input"
echo >&2 "Output: $output"

mkdir -p "$(dirname "$output")"

tally \
    -i "$input" \
    -o - \
    --nozip \
    --with-quality \
| $mapper \
    --all --best --strata \
    --threads $num_threads \
    "$index" \
    -q \
    --sam \
    - \
| samtools view -Sb -F 0x4 - \
| samtools sort -m $max_mem - "${tmp_output%.bam}"

samtools index "$tmp_output"

echo >&2 mv "$scratch_dir"/* "$(dirname "$output")"
mv "$scratch_dir"/* "$(dirname "$output")"
rm -rf "$scratch_dir"
