# First look at quantification of SINEs

```{r set-options, echo=FALSE}
library = function (...)
    suppressMessages(base::library(..., warn.conflicts = FALSE, quietly = TRUE))

library(modules)
import('knitr_init')
library(dplyr)
library(reshape2)
library(ggplot2)
options(stringsAsFactors = FALSE)
knitr::opts_knit$set(fig.path = 'figure/sine-',
                     cache.path = 'cache/sine-')
```

Load the result files.

```{r load-data}
result_parent = './results/bowtie/sines/express'
result_folders = list.files(result_parent, pattern = 'PolIII', include.dirs = TRUE, full.names = TRUE)
result_files = vapply(result_folders, file.path, character(1), 'results.xprs')
results = sapply(result_files, read.table, sep = '\t', header = TRUE, simplify = FALSE)
counts = `colnames<-`(sapply(results, function (x) x$tot_counts), NULL)

control_folders = list.files(result_parent, pattern = 'Input', include.dirs = TRUE, full.names = TRUE)
control_files = vapply(control_folders, file.path, character(1), 'results.xprs')
controls = sapply(control_files, read.table, sep = '\t', header = TRUE, simplify = FALSE)
control_counts = `colnames<-`(sapply(controls, function (x) x$tot_counts), NULL)
```

Merge replicates by averaging.

```{r merge-counts}
get_condition_table = function (filenames) {
    dos = sub('.*(do\\d+).*', '\\1', filenames)
    conditions = strsplit(sub('.*(brain|liver).*BL6([^_]+).*', '\\1-\\2', filenames), '-')
    tissues = sapply(conditions, function (cond) switch(cond[1], brain = 'Brain', liver = 'Liver'))
    stages = sapply(conditions, function (cond) toupper(cond[2]))
    data.frame(DO = dos, Tissue = tissues, Stage = stages, row.names = NULL) %>%
        mutate(Condition = paste(Tissue, Stage, sep = '-')) %>%
        tbl_df()
}

merge_replicates = function (counts, conditions)
    `colnames<-`(counts, conditions$DO) %>%
        melt(varnames = c('SINE', 'DO'), value.name = 'Count') %>%
        inner_join(conditions, by = 'DO', copy = TRUE) %>%
        group_by(SINE, Condition) %>%
        summarize(Count = sum(Count)) %>%
        tbl_df()

conditions = get_condition_table(result_files)
control_conditions = get_condition_table(control_files)

long_counts = merge_replicates(counts, conditions)
control_long_counts = merge_replicates(control_counts, control_conditions)
```

The distribution of counts:

```{r summary, fig.width=12}
asinh_trans = function ()
    scales::trans_new('asinh', asinh, sinh, domain = c(-Inf, Inf))

scale_y_asinh = function (...)
    scale_y_continuous(..., trans = asinh_trans())

total_counts = rbind_list(mutate(long_counts, Experiment = 'PolIII'),
                          mutate(control_long_counts, Experiment = 'Input'))

ggplot(total_counts, aes(x = Condition, y = Count)) +
    geom_boxplot(aes(fill = Experiment)) +
    scale_y_asinh()

ggplot(filter(total_counts, Count != 0), aes(x = Condition, y = Count)) +
    geom_boxplot(aes(fill = Experiment)) +
    scale_y_asinh(name = 'Counts (without zeros)')
```
