#!/usr/bin/env bash

infile="$1"
outfile="$2"

< "$infile" \
    tail -n +4 \
    | gawk -vOFS='\t' '{
        strand = $9 == "C" ? "-" : "+"
        class = $11

        # Features according to SOFA.obo
        switch (class) {
            case /^SINE/: feature = "dispersed_repeat"; break;
            case /^LINE/: feature = "dispersed_repeat"; break;
            case /^LTR/: feature = "dispersed_repeat"; break;
            case "tRNA": feature = "tRNA"; break;
            case "rRNA": feature = "rRNA_primary_transcript"; break;
            default: feature = "repeat_region";
        }

        # 100% - %substitutions - (%insertions + %deletions) / 2
        # NB: insertions and substitutions are counted half because otherwise a
        # bad alignment could cause a score < 0 (at most, #indels < 2 * #bp).
        score = 100 - $2 - 0.5 * ($3 + $4)

        # The range of the match inside the repeat consensus sequence
        range = strand == "+" ? ($12 "-" $13) : ($14 "-" $13)

        print $5, "RepeatMasker", feature, $6, $7, score, strand, ".", \
            "Name=\"" $10 "\"; Derives_from=\"" class "\"; Range=\"" range "\""
    }' \
    > "$outfile"
